### ISSUE TITLE
Issabel4

### ISSUE THREAD

**Issue by rafalzda** [qarmin/Rewelacyjne-OpenSource#1]
Wirtualna centrala telefoniczna pod Centosem 7 - opensource, ma wbudowany VPN i CRM jak również moduł Call Center
https://www.issabel.org
A tutaj jest przykład konfiguracji z polskim FCNem :)
https://manwhoworksinit.eu/2019/04/02/37/fcn-asterisk-issabel-jak-skonfigurowac

**Comment by qarmin** [comment]
Dodano w 8ff33943f574af2ad44ac5bc7786a03c2550bfdc
