### ISSUE TITLE
Sugestie

### ISSUE THREAD

**Issue by ghost** [qarmin/Rewelacyjne-OpenSource#15]
**Tworzenie obiektów 3D**
Meshroom - https://alicevision.github.io/#meshroom
Meshlab - http://www.meshlab.net/

**Pakiet Biurowy**
Apache OpenOffice - https://www.openoffice.org/pl/

**Rysowanie/Malowanie(Grafika Rastrowa/Zwykła)**
GIMP - https://www.gimp.org/

**Comment by qarmin** [comment]
Dodano w 553f6b3531f0213574b74df074358bf7f0cc70b5
Gimp jest obecny w kategorii "Organizacja i Edycja Zdjęć", gdzie według mnie bardziej pasuje(staram się unikać duplikowania programów)
