### ISSUE TITLE
Kolejność alfabetyczna

### ISSUE THREAD

**Issue by gpon64** [qarmin/Rewelacyjne-OpenSource#16]
Grupy (edytor tekstu, odtwarzacz muzyki itd) powinny być ułożone w kolejności alfabetycznej. Aktualnie dokument jest "ciężko czytelny".

**Comment by qarmin** [comment]
Nie jestem do końca pewien czy to jest dobry pomysł.

Początkowo gdy tworzyłem listę tylko dla siebie i rodziny, starałem się aby kategorie potrzebne większej ilości ludzi np. Edytory tekstu były wyżej niż Tworzenie i modelowanie 3D, ale z czasem granice się zbyt rozmyły i rzeczywiście panuje teraz niewielki chaos.

Co do kolejności programów na liście, to też myślę, że nie powinna być ona ustawiona wzgędem alfabetu, lecz przydatności programu np. LibreOffice przed OpenOffice gdyż OpenOffice traci coraz więcej deweloperów i użytkowników

**Comment by qarmin** [comment]
W sumie, już zam nieco zaczynałem się gubić przy dodawaniu nowych wpisów.
Dodano w 1b6a6ca3041cc8aa96c9813bf9d6c81d96fafa31
