### ISSUE TITLE
Moje narzędzia

### ISSUE THREAD

**Issue by pbies** [qarmin/Rewelacyjne-OpenSource#19]
Niekoniecznie open-source ale przeważnie darmowe, a przede wszystkim dobrze zaprogramowane aplikacje:

- AutoStitch do panoram
- CrystalDiskInfo, CrystalDiskMark, AIDA64, HWiNFO do hardware i benchmarking
- foobar2000 do muzyki
- GitHub Desktop do repozytoriów kodu
- IrfanView do oglądania zdjęć
- MalwareBytes Antimalware jako antywirus (chociaż przy Win Defender raczej nie trzeba)
- Mozilla Thunderbird do poczty
- Oracle VirtualBox do maszyn wirtualnych
- Paint.NET do grafiki ale raczej pojedyncze zdjęcia
- PotPlayer do wideo/filmów bo MPC-HC już nie rozwijany a MPC-BE jest niedopracowany
- qBittorrent do p2p
- RawTherapee do zdjęć masowo
- Signal do komunikacji bo Whatsapp śledzi i są podejrzenia wobec niego, tak samo Messenger
- Sublime Text - edytor do .txt z wieloma funkcjami, również do plików binarnych (hex)
- Total Commander do obsługi plików, nie ma obecnie lepszego narzędzia
- VSCodium bo Visual Studio jest ogromne, a VS Code nadal wysyła staty do MS
- WinRAR, 7-zip do archiwów
- WPS Office 2019 - pakiet biurowy

**Comment by qarmin** [comment]
Niestety, ale większość aplikacji nie jest udostępniana na licencji open source, a te które są, zostały już dodane do listy.
