### ISSUE TITLE
Systemy: MX Linux

### ISSUE THREAD

**Issue by Fibogacci** [qarmin/Rewelacyjne-OpenSource#2]
Strona projektu: https://mxlinux.org/
Strona Forum: https://forum.mxlinux.org/

Powody, dla których warto, aby MX Linux znalazł się na liście Rewelacyjne-OpenSource w dziale Systemy:
- łatwy dla początkujących, wygodny dla zaawansowanych, stabilny i wydajny dla wszystkich,
- od 7 kwietnia 2019 (i od wersji MX Linux 18.2) dostępny w wersji polskiej (instalator, system i MX Narzędzia są w całości przetłumaczone na język polski),
- MX Narzędzia ogromnie ułatwiają życie, szczególnie początkującym i nietechnicznym użytkownikom,
- rozbudowane opcje wykorzystania systemu w trybie Live-USB (na pendrivie/pamięci) - Persistence czyli zapisywanie dokonanych zmian na stałe na pendrivie oraz Remaster czyli tworzenie własnej wersji systemu do dalszej dystrybucji
- szybko rosnąca popularność na świecie (1 miejsce na listach Distrowatch.com w ostatnich 6 i 3 miesiącach, 30 dniach, 7 dniach; 2 miejsce w ostatnich 12 miesiącach),
- oparty na Debianie, wykorzystuje XFCE, posiada własne repozytorium MX Test (nowsze pakiety niż w repozytorium Debian Stable).

**Comment by qarmin** [comment]
Dodano w 8ff33943f574af2ad44ac5bc7786a03c2550bfdc
