### ISSUE TITLE
Dlaczego nie warto korzystać z open source i dlaczego open source to rak

### ISSUE THREAD

**Issue by PELock** [qarmin/Rewelacyjne-OpenSource#3]
7 powodów, dla których nie warto korzystać z open source

https://www.beningo.com/7-reasons-to-avoid-open-source-software/

Open source sucks

https://www.hackerfactor.com/blog/index.php?/archives/415-Open-Source-Sucks.html

**Comment by srsbiz** [comment]
Pierwszy artykuł niby z 2017 ale przemyślenia jakby z 2007, poza tym konkluzja mówi co innego niż tytuł zgłoszenia:

> By no means am I against open source software. It’s been extremely helpful and beneficial in certain circumstances.

Oraz followup do drugiego artykułu:
https://www.hackerfactor.com/blog/index.php?/archives/416-Open-Source-Rocks.html

Także kiepski dobór linków do poparcia kiepskiego stwierdzenia.
