### ISSUE TITLE
OpenLoco - Klon Chris Sawyer's Locomotion zdekompilowany i napisany w C++

### ISSUE THREAD

**Issue by Zcooger** [qarmin/Rewelacyjne-OpenSource#4]
https://github.com/OpenLoco/OpenLoco

**Comment by qarmin** [comment]
Dodane w 802be62b205c686749567fa1eac5608cc7f4e839

**Comment by qarmin** [comment]
Usunięte z listy w 553f6b3531f0213574b74df074358bf7f0cc70b5 , z powodu konieczności posiadania zamkniętoźródłowej gry do działania.
