### ISSUE TITLE
OpenRCT2 - Klon Rollercoaster Tycoon 2 zdekompilowany i napisany w C++

### ISSUE THREAD

**Issue by Zcooger** [qarmin/Rewelacyjne-OpenSource#5]
https://github.com/OpenRCT2

**Comment by PELock** [comment]
Ukradli cudzy kod źródłowy i wydali go na GNU GPLv3

https://github.com/OpenRCT2/OpenRCT2#5-licence

https://www.reddit.com/r/openrct2/comments/3xaplc/how_is_this_licensed/

Może ktoś mógłby ukraść ich kod i wydać to na komercyjnej licencji?

**Comment by Zcooger** [comment]
A czy przypadkiem nie korzystają z faktu, że na terenie europy możliwa jest inżynieria wsteczna?
Nigdzie nie ma info o tym, że komuś ukradli, jakieś źródło?

**Comment by PELock** [comment]
Gdzie jest zezwolenie od oryginalnego developera? Nigdzie, to zwykła kradzież cudzego projektu i chamskie publikowanie na licencji GNU GPLv3.

Jest zezwolona tylko w niektórych przypadkach tzw. "reverse engineering for interoperability", a branie całej gry, wszystkich grafik, wyciąganie całego kodu gry pod to nie podchodzi.

https://reverseengineering.stackexchange.com/questions/13439/are-the-eu-laws-preventing-reverse-engineering-of-software-products

**Comment by Zcooger** [comment]
Projekt OpenRCT2 nie korzysta z żadnych oryginalnych zasobów gry Rollercoaster Tycoon. Jest to jedynie odtworzenie oryginalnego silnika gry. Można przekonać się o tym próbując uruchomić program, który na wstępie zapyta o katalog instalacji Rollercoaster Tycoon. OpenRCT2 ma się dobrze i nie ma dowodów na to, że korzysta z jakiegokolwiek kradzionego lub nie kodu źródłowego Rollercoaster Tycoon. Kod źródłowy mógł powstać na podstawie oryginału a nie w wyniku kopiowania go. Gdyby korzystali z zasobów płatnych sprawa poszłaby do sądu a projekt dawno by został zamknięty.

**Comment by qarmin** [comment]
Niestety ale gra korzysta z zamkniętych/własnościowych zasobów, które są niezbędne do jej odpalenia. Kod źródłowy według mnie jest w porządku lecz nie oferuje możliwości odpalenia gry bez kupienia pierwowzoru.
