### ISSUE TITLE
HackTV Transmiter Telewizyjny

### ISSUE THREAD

**Issue by Zcooger** [qarmin/Rewelacyjne-OpenSource#6]
Generator i transmiter analogowego sygnału telewizyjnego modulowanego kablowo/satelitarnie i niemodulowanego z wyjściem do pliku, dla SDR HackRF i chipsetu Fresco FL2000 w adapterach USB 3.0>VGA. Wytwarza pliki baseband gotowe do obróbki lub transmisji w standardzie D2MAC, NTSC, PAL i SECAM z dźwiękiem stereo analogowym oraz NICAM, z możliwością zastosowania systemu kodowania dla dekoderów i odbiorników satelitarnych Nagravision Syster, Videocrypt, Eurocrypt i wkrótce Discret11.

https://github.com/fsphil/hacktv/

**Comment by qarmin** [comment]
Wydaje mi się, że ten program jest jedynie dostępny z linii komend, jeśli tak jest to niestety nie będę mógł go wpisać ponieważ nie podchodzi do zasady posiadania GUI.

**Comment by qarmin** [comment]
Dodano w  fd507844d5ffacceda006a4ceeabcfb1e8e41913
