### ISSUE TITLE
Kilka z mojej strony :D

### ISSUE THREAD

**Issue by houk001** [qarmin/Rewelacyjne-OpenSource#8]

**Comment by houk001** [comment]
Soft do deduplikacji plików graficznych  \AntiDupl.NET-2.3.8  http://antidupl.sourceforge.net/english/download.html
Sprawdzanie zajętości dysku  Spacesniffer http://www.uderzo.it/main_products/space_sniffer/

**Comment by ireun** [comment]
To ja się podepnę.. Program do screenshotów pod Windows: https://github.com/ShareX/ShareX

**Comment by houk001** [comment]
Nagrywarka CD pod Windows 
ImgBurn https://www.imgburn.com/

**Comment by qarmin** [comment]
AntiDupl.NET i Sharex dodano w 802be62b205c686749567fa1eac5608cc7f4e839
ImgBurn i SpaceSniffer nie są programami otwartymi
